basehub:
    jupyterhub:
        hub:
            config:
                GitHubOAuthenticator:
                    client_id: ENC[AES256_GCM,data:AFpmKZj1WUR16TgZie0EBkj70ko=,iv:alwXa0cN1+WpgwH9jEOzoNkS3CHCd859RIRyucic0uc=,tag:hLyemMd3pngkqib1dYZ/Uw==,type:str]
                    client_secret: ENC[AES256_GCM,data:t4vIGiZX4a2htkGZUy6GYfpegS5ggjoipSu8amzL/4mGHKVIoyNHtg==,iv:WM5jvoFJHmpnVlQWzPSY3Elu+Y+wF1cuEBAy/OtFND8=,tag:5JulcZMl+6vQ4dlTl4Lbjw==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:870461445243:alias/hub-deploy-key
          created_at: "2025-11-11T04:11:10Z"
          enc: AQICAHgQoFnFdS0foDgPD5oSEhmSHosc9BK41hUPUoWe6jzOLgHi3esPqCNVHE0I7RyFY43bAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3kZjY0yEj9pW1+9xAgEQgDu3sxb1fjXlhUHCuhv5Oq0haza4HpjqJ1Q8WFWNjrL8/xJvIt6tKNxqYgaCktmdVCoXgVTUhE25ag+3vg==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-11T04:11:10Z"
    mac: ENC[AES256_GCM,data:MJZUfq16UTCpGAvR6SSspPUFIU9pkmhCPVkRr9ylrabdAB4s9fsbczoJRV5z8zCU5nVIPW/wZzbLngmVTvKCrGXyWTnCCPuq4q6MFiJIimbbtz0n1ZE6af04kxP/cBaQYtgcH35smPPjuSZuP+VFnH8lc64LYZeknsmtHqV2F2g=,iv:zCzLG9IJtQWmBjydfueYy96RGTR/LzBBpi2WIKSCkZQ=,tag:R2Apqa/qzWiMBRGQsjz+cA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
