basehub:
    jupyterhub:
        hub:
            config:
                GitHubOAuthenticator:
                    client_id: ENC[AES256_GCM,data:rBb3P6MdMFjomDgHG/HWsVs5KVU=,iv:rPsAfVbY2PYGyRJkFqgrIqx5Dz1labNVu4w1gkv82co=,tag:MCaFHhUjRt/4E3aFV/yp7Q==,type:str]
                    client_secret: ENC[AES256_GCM,data:YnfiRxatjRJVyJ29Qs0fBCy1BLQgRPvuzDzJ+TAmncqe5g6DL9VXZQ==,iv:f3zr59c8+Og/t5ffNjzYTzpoKBm8j6pHzkScD1y5xCQ=,tag:GjVUTYpQeQudUNefsynBLA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:870461445243:alias/hub-deploy-key
          created_at: "2025-11-11T04:10:56Z"
          enc: AQICAHgQoFnFdS0foDgPD5oSEhmSHosc9BK41hUPUoWe6jzOLgGXBPRZv+ZjyluW04HaXyybAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkriGrksWVDZ5+CmrAgEQgDuHwejjtMV8zbUzyWyTSjkbOo2y0FQaRKYFuDL1iRQbXop7a9tZBXXnbThMtR7xTgT3r6ImEUhTrha/EQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-11T04:10:56Z"
    mac: ENC[AES256_GCM,data:B6arFnAhgmOC3W1SGJTRePatuDf+iJTsO2v25+U+HKpBPOq05iCpQ7VrGkPM8fIUG/Gl6czm8Bs4JUr4mc5l3vS0x+5cbWak2PnNkJQc8tVHh9f5s8FpqsV0htSkq1NXxYjNl5hAuNKc3P4D+p9DpBwukPREwkxzHuiKiGPDMzc=,iv:jPm+6FhGjcorKLZ3UlxtRtAEBca6OdXQeAs0nbrS3QM=,tag:Zh0CrvFZkLeZiSbIXC3Z6w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
