jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:04hOr1O6+0k/mA==,iv:gVPM0VBolm6pYWCJTh+NO0eiFdhUmzRTJS/lEMXFUdA=,tag:1zQbr1lggrPCQkbgAukpug==,type:str]
        client_secret: ENC[AES256_GCM,data:IyhF8qrQLFspvYERDuezCQ==,iv:6+EgE3EqcMqWV2utrwZrTE8DbHZ+DNBIlxD1QKZFAwg=,tag:mCA/9huQs9AApV6/M42BUQ==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-west-2:870461445243:alias/hub-deploy-key
      created_at: "2025-11-13T00:04:40Z"
      enc: AQICAHgQoFnFdS0foDgPD5oSEhmSHosc9BK41hUPUoWe6jzOLgFTS3YN2cSz8AfDaSzV7vfCAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM4d+6+/5XePsm55u1AgEQgDvH+rMeZZyWOf3Gr/SI3pGuYpFcNflX3vQKWe2vcsWKyuQev1VQ9ubiNfR7bkORCYqHdATrBWvosLBCNQ==
      aws_profile: ""
  lastmodified: "2025-11-28T04:55:12Z"
  mac: ENC[AES256_GCM,data:8176wtIN0AiaFE4Nf7K2Oxby9uaVouf+a8cK9X1k352yMKoJPxwiReD7SPKoGZ3k4Dh7VSgGWssOFDwKenNWa/XyWBiwOoQVNv2iEwagaBhPAj675WujF27jjr3QdFAyCpw4zJIOXR/A290O1EqhjNKuyTJ0U5Ld/LSSQ5f9j+o=,iv:smW+AXvOyTW+ve+lqpb+kkrV2F0J0kpvi3hEWGep/lc=,tag:lk40Fe6cKn2hsbkwSelm5w==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
