jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:5kZkT9QKgYDjy6H2B77HVnhlMgs=,iv:8AQlAWoD1QLZS4CFEU387x8h+WniUejrP1PeQM1k40c=,tag:UWf8SGunyYlyT8Xx6LXLjg==,type:str]
                client_secret: ENC[AES256_GCM,data:b2pjJAUmOkhUJsuM6bI2/zY304GTzPwVMTSEX4ypTugl86KcLkJofQ==,iv:bS5uFoH6CSwPCstLjAuVCxcmW8WvpbtQxDhTG2/WtKg=,tag:K5q06l7u/QoPTNZwiKbI8g==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:870461445243:alias/hub-deploy-key
          created_at: "2025-11-11T23:06:05Z"
          enc: AQICAHgQoFnFdS0foDgPD5oSEhmSHosc9BK41hUPUoWe6jzOLgEVjisyqRN3VxLIc2Rgz2gvAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMBo4bJZKtiSAu+9XNAgEQgDvEKXodu82I6hpwI/mt9AnvOAKejtRVzMu+RJ9YCbfnvQ0tVNI08TGWIZ0gAtUMxZLMp1+eF9Tc794ajQ==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-11T23:06:05Z"
    mac: ENC[AES256_GCM,data:V2oZOYOKEiDjRnI/oAMJ4YT5w0iVBzFwAoIqOME6dER6fV1myG9NtAu1/xU5D9rakVydFfVtosIC92sQ7qc1PqR4K7KT4jzSUHPt3qeELki/0ESKdpC9OXwleNkmyG3YrBiFBU7FulRxO09qJR99OLvzpu3plSVWwWwUl/Flal0=,iv:bmvKyZeGvg1Px9rZGOo1GbMnO+wbM1WdHqk7HTiexAU=,tag:4pNqJbGsHIPmRv7Plko03w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
