jupyterhub:
    hub:
        config:
            GitHubOAuthenticator:
                client_id: ENC[AES256_GCM,data:Xd3vCKAgusI4wlFZZGfyWSwAu0U=,iv:Mj7CAO6NcqtHwj99a/mF3xpymrbCi5vCa3E0QXDerZs=,tag:AHEDZQwObf0c/AD/cU/rgg==,type:str]
                client_secret: ENC[AES256_GCM,data:gzgZnIOyRB8t+bDDYeNa2jLOAL7jKU8DLnhOmn34jjfvqei0Jh6z1Q==,iv:250dWuB1sp177WDf+JNEfCA/4YBbfLbAebf2DipH1GI=,tag:5LLQ5NImgkRo0g6atfDszg==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:us-west-2:870461445243:alias/hub-deploy-key
          created_at: "2025-11-11T23:05:46Z"
          enc: AQICAHgQoFnFdS0foDgPD5oSEhmSHosc9BK41hUPUoWe6jzOLgEDOBSTYbd7VPKAydEjfsnfAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9VbF3+Z72XKJg6dGAgEQgDvDL1scZFg7q0Lv4rgSUvpra5MrxwEscLIw0gaLjdtFfs4SnxGGUPzOJgMzz4fRRWk34oLHBrkqWHXtEw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-11-11T23:05:46Z"
    mac: ENC[AES256_GCM,data:IwhAWmNl2yVaAuWr0qkXeiXUOAjgrH3ZEugRspyFFQlyXa//y5V1NHpTThwyQzoLrt08LfWrhyR74yzAAPD8SLK5uOReC1Qt9htJWdZ/VDRFAuotkbuSPQRsFkkcpo/gGupFEQq2zjkwzld0kYxMGrPOvMqEGzcYFgSwGQzhL74=,iv:SvpPSzTSN0kH/3VTe+6Qx/uigbLICiUdTHjopJsPAHA=,tag:DzyZJ+hS2VEu7bzZE/i1Og==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
