jupyterhub:
  hub:
    config:
      GenericOAuthenticator:
        client_id: ENC[AES256_GCM,data:q4JCbOTSBwBKBA==,iv:3XFDKAMpji7A8VplOPXP0fVOqvTmn+EPTKEWjwY4wAg=,tag:Bj5E73lEGHZZ26rpzPEjUQ==,type:str]
        client_secret: ENC[AES256_GCM,data:R+t1k/UTki6gIYThp88Csw==,iv:BiX9y/pHT6Jps3KeBUWXNQWIbW4AViogTrDC1xgccvo=,tag:jsS9kHYDbdlBvyfZ9+bmLA==,type:str]
sops:
  kms:
    - arn: arn:aws:kms:us-west-2:870461445243:alias/hub-deploy-key
      created_at: "2025-12-10T21:03:47Z"
      enc: AQICAHgQoFnFdS0foDgPD5oSEhmSHosc9BK41hUPUoWe6jzOLgExQGjSqJiThKxVPn3ykd5bAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMqNLhJKEKkcLza/imAgEQgDsFsbBwwCVvfaW6WwHs6dZlOQmsLEBtH4751wn1lC/eKYAEmFDrS13fZ36v3dWuW+oDgef7ifyuEcHfog==
      aws_profile: ""
  lastmodified: "2025-12-10T21:04:54Z"
  mac: ENC[AES256_GCM,data:pIrpRm7CXdZcr6kgr3MMLPRypqqBUHFSMLH7DZnW1v5tMxuCXYz9MfZS9wk3ogsCgI10Feax4fK9n297Q5/HYIp5yrm8tZXhb5KrIzxBEXoR884UIwb0fLxYiKcdg5K0AX4E134uyj2K/t6YCahNGGlYFOGf8F2YCrV9tLs9ZvE=,iv:pcX7qnPbSC5rbzRLE+kCnQFcxUDSyTmUsOn8NGivU1I=,tag:+908zbn3hgQc7ShccK5zBQ==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.11.0
