# userServiceAccount:
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::870461445243:role/grss-veda-staging
dask-gateway:
  gateway:
    backend:
      scheduler:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: staging
      worker:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: staging

jupyterhub:
  ingress:
    hosts: [staging-hub.veda.grss.cloud]
    tls:
    - hosts: [staging-hub.veda.grss.cloud]
      secretName: https-auto-tls
  hub:
    config:
      GenericOAuthenticator:
        oauth_callback_url: https://hub.veda.grss.cloud/hub/oauth_callback
  singleuser:
    nodeSelector:
      2i2c/hub-name: staging

# binderhub-service:
#   dockerApi:
#     nodeSelector:
#       2i2c/hub-name: staging
#   config:
#     KubernetesBuildExecutor:
#       node_selector:
#         2i2c/hub-name: staging
#     BinderHub:
#       image_prefix: quay.io/imagebuilding-non-gcp-hubs/nasa-ghg-staging-

jupyterhub-home-nfs:
  eks:
    volumeId: vol-057a723a1f8a8db74
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 1
nfs:
  pv:
    serverIP: 10.100.250.195
