# userServiceAccount:
#   annotations:
#     eks.amazonaws.com/role-arn: arn:aws:iam::870461445243:role/grss-veda-staging
dask-gateway:
  gateway:
    backend:
      scheduler:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: staging
      worker:
        extraPodConfig:
          nodeSelector:
            2i2c/hub-name: staging

jupyterhub:
  ingress:
    hosts: [hub.staging.veda.grss-ieee.org]
    tls:
    - hosts: [hub.staging.veda.grss-ieee.org]
      secretName: https-auto-tls
  hub:
    config:
      GenericOAuthenticator:
        authorize_url: https://auth.staging.veda.grss-ieee.org/realms/veda/protocol/openid-connect/auth
        token_url: https://auth.staging.veda.grss-ieee.org/realms/veda/protocol/openid-connect/token
        userdata_url: https://auth.staging.veda.grss-ieee.org/realms/veda/protocol/openid-connect/userinfo
        oauth_callback_url: https://hub.staging.veda.grss-ieee.org/hub/oauth_callback
        logout_redirect_url: https://auth.staging.veda.grss-ieee.org/realms/veda/protocol/openid-connect/logout?client_id=jupyterhub&post_logout_redirect_uri=https%3A%2F%2Fhub.staging.veda.grss-ieee.org
  singleuser:
    nodeSelector:
      2i2c/hub-name: staging
    profileList:
    - display_name: Choose your environment and resources
      default: true
      profile_options:
        resource_allocation:
          display_name: Resource Allocation
          choices:
            mem_1_9:
              display_name: 1.9 GB RAM, upto 3.7 CPUs
              allowed_groups:
                - JupyterHub Admin
                - JupyterHub Basic User
                - JupyterHub User
              kubespawner_override:
                mem_guarantee: 1991244775
                mem_limit: 1991244775
                cpu_guarantee: 0.2328125
                cpu_limit: 3.725
                node_selector:
                  node.kubernetes.io/instance-type: r5.xlarge
              default: true
            mem_3_7:
              display_name: 3.7 GB RAM, upto 3.7 CPUs
              allowed_groups:
                - JupyterHub Admin
                - JupyterHub Basic User
                - JupyterHub User
              kubespawner_override:
                mem_guarantee: 3982489550
                mem_limit: 3982489550
                cpu_guarantee: 0.465625
                cpu_limit: 3.725
                node_selector:
                  node.kubernetes.io/instance-type: r5.xlarge
            mem_7_4:
              display_name: 7.4 GB RAM, upto 3.7 CPUs
              allowed_groups:
                - JupyterHub Admin
                - JupyterHub User
              kubespawner_override:
                mem_guarantee: 7964979101
                mem_limit: 7964979101
                cpu_guarantee: 0.93125
                cpu_limit: 3.725
                node_selector:
                  node.kubernetes.io/instance-type: r5.xlarge

# binderhub-service:
#   dockerApi:
#     nodeSelector:
#       2i2c/hub-name: staging
#   config:
#     KubernetesBuildExecutor:
#       node_selector:
#         2i2c/hub-name: staging
#     BinderHub:
#       image_prefix: quay.io/imagebuilding-non-gcp-hubs/nasa-ghg-staging-

jupyterhub-home-nfs:
  eks:
    volumeId: vol-0c2490fecf0b20f7e
  quotaEnforcer:
    config:
      QuotaManager:
        hard_quota: 1
nfs:
  pv:
    serverIP: 10.100.173.82